backend:
  name: github
  repo: SamDark0202/page-unicv-polo-manaus-flores
  branch: main
  base_url: https://decap-cms-oauth-vercel.vercel.app # Um servidor de autenticação pronto para uso

media_folder: "img/uploads" # Onde as imagens dos posts serão salvas
public_folder: "/img/uploads"

collections:
  - name: "blog"
    label: "Postagens do Blog"
    folder: "src/content/posts" # O CMS vai criar os arquivos aqui
    extension: "json" # Para facilitar a leitura no React (App.tsx)
    create: true
    fields:
      - { label: "ID", name: "id", widget: "number" }
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Resumo", name: "excerpt", widget: "text" }
      - { label: "Conteúdo", name: "content", widget: "markdown" }
      - { label: "Imagem", name: "image", widget: "image" }
      - { label: "Data", name: "date", widget: "datetime" }