backend:
  name: github
  repo: SamDark0202/page-unicv-polo-manaus-flores
  branch: main
  base_url: https://decap-cms-oauth-vercel.vercel.app

media_folder: "public/img/uploads"
public_folder: "/img/uploads"

collections:
  - name: "blog"
    label: "Postagens do Blog"
    folder: "public/posts"
    extension: "json"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Resumo", name: "excerpt", widget: "text" }
      - { label: "Conteúdo", name: "body", widget: "markdown" }
      - { label: "Imagem", name: "image", widget: "image" }
      - { label: "Data", name: "date", widget: "datetime" }